/**
 * Canonical list of audit actions. Audit logging is a core requirement, so the
 * set of actions is centralised here to prevent magic strings drifting apart.
 */
export const AUDIT_ACTIONS = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  ADMIN_CREATED: 'ADMIN_CREATED',
  ADMIN_UPDATED: 'ADMIN_UPDATED',
  ADMIN_DISABLED: 'ADMIN_DISABLED',

  SUPPORT_CREATED: 'SUPPORT_CREATED',
  SUPPORT_UPDATED: 'SUPPORT_UPDATED',
  SUPPORT_DISABLED: 'SUPPORT_DISABLED',

  USER_VIEWED: 'USER_VIEWED',
  USER_UPDATED: 'USER_UPDATED',
  USER_BANNED: 'USER_BANNED',
  USER_UNBANNED: 'USER_UNBANNED',
  USER_DELETED: 'USER_DELETED',

  CLINIC_VIEWED: 'CLINIC_VIEWED',
  CLINIC_UPDATED: 'CLINIC_UPDATED',
  CLINIC_BANNED: 'CLINIC_BANNED',
  CLINIC_UNBANNED: 'CLINIC_UNBANNED',
  CLINIC_DELETED: 'CLINIC_DELETED',

  DOCTOR_CREATED: 'DOCTOR_CREATED',
  DOCTOR_UPDATED: 'DOCTOR_UPDATED',
  DOCTOR_DELETED: 'DOCTOR_DELETED',

  FAQ_CREATED: 'FAQ_CREATED',
  FAQ_UPDATED: 'FAQ_UPDATED',
  FAQ_DELETED: 'FAQ_DELETED',

  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
