#!/usr/bin/env node
/**
 * Reads NGROK_URL from the root .env and writes .env.local into every app so
 * they all point at the same backend. This is the ONE place the URL lives.
 *
 *   root .env  ──►  frontend/.env.local
 *                   admin/.env.local
 *                   OnChikitsa_user/.env.local
 *                   OnChikitsa_clinic/.env.local
 *
 * Mobile apps run on a real device, so localhost is unreachable there — they
 * MUST use the ngrok URL. Web apps fall back to localhost when NGROK_URL is empty.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
require('dotenv').config({ path: path.join(root, '.env') });

const NGROK_URL = (process.env.NGROK_URL || '').trim().replace(/\/+$/, '');
const LOCAL_API = `http://localhost:${process.env.PORT || 5000}`;

const webApiUrl = NGROK_URL || LOCAL_API;
const mobileApiUrl = NGROK_URL || LOCAL_API;

const targets = [
  { dir: 'frontend', url: webApiUrl },
  { dir: 'admin', url: webApiUrl },
  { dir: 'OnChikitsa_user', url: mobileApiUrl },
  { dir: 'OnChikitsa_clinic', url: mobileApiUrl },
];

if (!NGROK_URL) {
  console.warn('\n[sync-env] ⚠  NGROK_URL is empty in root .env.');
  console.warn(`[sync-env]    Web apps will use ${LOCAL_API}.`);
  console.warn('[sync-env]    A real Android device CANNOT reach localhost — set');
  console.warn('[sync-env]    NGROK_URL in .env before running the mobile apps on a device.\n');
}

for (const t of targets) {
  const envPath = path.join(root, t.dir, '.env.local');
  const content =
    '# AUTO-GENERATED by scripts/sync-env.js — do not edit by hand.\n' +
    '# Change NGROK_URL in the root .env, then run `npm run sync-env`.\n' +
    `NEXT_PUBLIC_API_URL=${t.url}\n`;
  fs.writeFileSync(envPath, content);
  console.log(`[sync-env] ${t.dir}/.env.local -> NEXT_PUBLIC_API_URL=${t.url}`);
}
